{{- if and .Values.tunnel.enabled .Values.tunnel.createSecret .Values.tunnel.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.fullname" . }}-tunnel
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.tunnel.secretKey }}: {{ .Values.tunnel.credentials | b64enc }}
{{- end }}
